Config.EMSMacros = {
    { label = "ON DUTY", value = "EMS %name% %surname% : On Duty", description = "Start shift." },
    { label = "OFF DUTY", value = "EMS %name% %surname% : Off Duty", description = "End shift." },
    { label = "ON BREAK", value = "EMS %name% %surname% : On Break", description = "Temporary break status." },
    { label = "BACK BREAK", value = "EMS %name% %surname% : Back from Break", description = "Back from break." },
    { label = "STANDBY", value = "EMS %name% %surname% : On Standby", description = "Ready on standby." },
    { label = "EN ROUTE", value = "EMS %name% %surname% : En route to %location%", description = "Heading to scene." },
    { label = "ON SCENE", value = "EMS %name% %surname% : On scene at %location%", description = "Arrival on scene." },
    { label = "LEAVING SCENE", value = "EMS %name% %surname% : Leaving scene from %location%", description = "Scene departure." },
    { label = "RTB", value = "EMS %name% %surname% : Returning to hospital", description = "Return to base/hospital." },
    { label = "NEED PD", value = "EMS %name% %surname% : Need PD support at %location%", description = "Request police support." },
    { label = "NEED EXTRA EMS", value = "EMS %name% %surname% : Need additional EMS units at %location%", description = "Request extra EMS units." },
    { label = "PATIENT STABLE", value = "EMS %name% %surname% : Patient stable at %location%", description = "Patient condition update." },
    { label = "PATIENT CRITICAL", value = "EMS %name% %surname% : Patient critical at %location%, priority transport", description = "Critical patient update." },
    { label = "CPR", value = "EMS %name% %surname% : CPR in progress at %location%", description = "CPR status." },
    { label = "TRANSPORTING", value = "EMS %name% %surname% : Transporting patient to %input:\"Hospital\"%", description = "Patient transport status." },
    { label = "AT HOSPITAL", value = "EMS %name% %surname% : Arrived at %input:\"Hospital\"% with patient", description = "Hospital arrival." },
    { label = "PATIENT HANDED OVER", value = "EMS %name% %surname% : Patient handed over, available shortly", description = "Patient handover done." },
    { label = "UNAVAILABLE", value = "EMS %name% %surname% : Temporarily unavailable for %input:\"Minutes\"% minutes", description = "Short unavailable status." },
    { label = "AVAILABLE", value = "EMS %name% %surname% : Available for calls", description = "Back available." },
}
