Config.PoliceMacros = {
    { label = "10-0", value = '%input:"Callsign"% | Need a 10-0 situation report', description = "Request a status report with response code." },
    { label = "10-1", value = '%input:"Callsign"% | I am 10-1, weak signal.', description = "Signal is weak." },
    { label = "10-2", value = '%input:"Callsign"% | I am 10-2, receiving well.', description = "Signal is clear." },
    { label = "10-3", value = '%input:"Callsign"% | 10-3, stop radio chatter.', description = "Clear radio traffic." },
    { label = "10-4", value = '%input:"Callsign"% | 10-4, copy.', description = "Acknowledgment." },
    { label = "10-6", value = '%input:"Callsign"% | I am 10-6 for %input:"Minutes"% minutes.', description = "Short unavailable status." },
    { label = "10-7", value = '%input:"Callsign"% | I am 10-7, out of service.', description = "Out of service." },
    { label = "10-8", value = '%input:"Callsign"% | I am 10-8, back in service.', description = "Back on duty." },
    { label = "10-9", value = '%input:"Callsign"% | 10-9, repeat that transmission.', description = "Ask to repeat." },
    { label = "10-10", value = '%input:"Callsign"% | Doing a 10-10 at %location%.', description = "Fight in progress." },
    { label = "10-11", value = '%input:"Callsign"% | Need a 10-11 on %input:"Name/Plate"%.', description = "MDT check request." },
    { label = "10-12", value = '%input:"Callsign"% | 10-12, stand by.', description = "Stand by." },
    { label = "10-13", value = '%input:"Callsign"% | 10-13 officer down at %location%!', description = "Officer down emergency." },
    { label = "10-20", value = '%input:"Callsign"% | My 10-20 is %location%.', description = "Current location." },
    { label = "10-23", value = '%input:"Callsign"% | 10-23, I am on scene.', description = "Arrived at scene." },
    { label = "10-25", value = '%input:"Callsign"% | 10-25, report to %input:"Meet point"%.', description = "Report in person." },
    { label = "10-31", value = '%input:"Callsign"% | Doing a 10-31 at %location%.', description = "Crime in progress." },
    { label = "10-32", value = '%input:"Callsign"% | Doing a 10-32 at %location%.', description = "Person with a gun." },
    { label = "10-38", value = '%input:"Callsign"% | Doing a 10-38 on %input:"Vehicle/Plate"% at %location%.', description = "Traffic stop." },
    { label = "10-41", value = '%input:"Callsign"% | 10-41, starting patrol.', description = "Going on patrol." },
    { label = "10-42", value = '%input:"Callsign"% | 10-42, heading back to PD.', description = "Back to PD." },
    { label = "10-47", value = '%input:"Callsign"% | Doing a 10-47 at %location%.', description = "Injured person." },
    { label = "10-50", value = '%input:"Callsign"% | Doing a 10-50 at %location%.', description = "Accident." },
    { label = "10-52", value = '%input:"Callsign"% | Need 10-52 EMS at %location%.', description = "Request EMS." },
    { label = "10-60", value = '%input:"Callsign"% | Doing a 10-60 at %location%.', description = "Carjacking." },
    { label = "10-71", value = '%input:"Callsign"% | 10-71 shots fired at %location%.', description = "Shots fired." },
    { label = "10-76", value = '%input:"Callsign"% | 10-76 enroute to %input:"Destination"%.', description = "Enroute." },
    { label = "10-77", value = '%input:"Callsign"% | Need 10-77 backup at %location%.', description = "Non-emergency backup." },
    { label = "10-78", value = '%input:"Callsign"% | Need 10-78 emergency backup at %location%!', description = "Emergency backup." },
    { label = "10-80", value = '%input:"Callsign"% | Doing a 10-80 pursuit on %input:"Vehicle"% from %location%.', description = "Pursuit in progress." },
    { label = "10-90", value = '%input:"Callsign"% | Doing a 10-90 at %location%.', description = "Robbery in progress." },
    { label = "10-91", value = '%input:"Callsign"% | Doing a 10-91 to %input:"Destination"%.', description = "Transport." },
    { label = "10-94", value = '%input:"Callsign"% | Doing a 10-94 on %input:"Vehicle"% near %location%.', description = "Reckless driver." },
    { label = "10-95", value = '%input:"Callsign"% | 10-95, suspect in custody.', description = "Suspect detained." },
    { label = "10-98", value = '%input:"Callsign"% | 10-98 at %input:"Facility"%.', description = "Jail break." },

    { label = "CODE 1", value = '%input:"Callsign"% | Going CODE 1.', description = "Routine response." },
    { label = "CODE 2", value = '%input:"Callsign"% | Going CODE 2.', description = "Lights only." },
    { label = "CODE 3", value = '%input:"Callsign"% | Going CODE 3.', description = "Lights and siren." },
    { label = "CODE 4", value = '%input:"Callsign"% | We are CODE 4, scene clear.', description = "No further units needed." },
    { label = "CODE 5", value = '%input:"Callsign"% | CODE 5 in area: %input:"Details"%.', description = "Area advisory." },
    { label = "CODE 6", value = '%input:"Callsign"% | CODE 6 at %location%, out of vehicle investigating.', description = "Investigation on foot." },
}
